# Generated by Django 2.2.2 on 2019-06-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190613_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='sadasd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(default='car factory', max_length=100),
            preserve_default=False,
        ),
    ]
